### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by NullVoxPopuli** [christopherthielen/check-peer-dependencies#52]
```
Ok to proceed? (y) y
/home/nvp/.npm/_npx/25bb3e225fb6eeb9/node_modules/check-peer-dependencies/dist/packageUtils.js:51
                throw new Error("WARN: Unable to resolve package " + dependency.name + " from " + packagePath);
                ^

Error: WARN: Unable to resolve package @ampproject/remapping from /home/nvp/Development/NullVoxPopuli/limber/apps/tutorial/node_modules/@babel/core
    at walkDependency (/home/nvp/.npm/_npx/25bb3e225fb6eeb9/node_modules/check-peer-dependencies/dist/packageUtils.js:51:23)
    at /home/nvp/.npm/_npx/25bb3e225fb6eeb9/node_modules/check-peer-dependencies/dist/packageUtils.js:59:74
    at Array.forEach (<anonymous>)

```

**Comment by eakkawat** [comment]
Same. This project is abandoned.
